const webDesign = {
  id: "web-design",
  data: [
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
  ],
};
const appDesing = {
  id: "app-design",
  data: [
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
  ],
};
const appProject = {
  id: "app-project",
  data: [
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: [
        {
          technologyName: "Redux",
          technologyUrl: "https://cdn.worldvectorlogo.com/logos/redux.svg",
          key: "a1",
        },
        {
          technologyName: "React",
          technologyUrl: "https://cdn.worldvectorlogo.com/logos/react-2.svg",
          key: "a2",
        },
      ],
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: [
        {
          technologyName: "Redux",
          technologyUrl: "https://cdn.worldvectorlogo.com/logos/redux.svg",
          key: "a1",
        },
        {
          technologyName: "React",
          technologyUrl: "https://cdn.worldvectorlogo.com/logos/react-2.svg",
          key: "a2",
        },
      ],
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
    {
      title: "1",
      key: "",
      urlThumbnail: "",
      description: "",
      technology: "",
      route: "https://www.google.com",
    },
  ],
};

export const dataProjects = [webDesign, appDesing, appProject];
